on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run:
          dotnet pack
          --configuration Release
          /p:Version=${VERSION}
          /p:PackageId=${CUSTOM_NUGET_PACKAGENAME}
          /p:RepositoryUrl=${CUSTOM_NUGET_REPOSITORYURL}
          /p:IncludeSymbols=true
          /p:SymbolPackageFormat=snupkg
          --no-build
          --output ./output
        env:
          CUSTOM_NUGET_PACKAGENAME: ${{ secrets.CUSTOM_NUGET_PACKAGENAME }}
          CUSTOM_NUGET_REPOSITORYURL: ${{ secrets.CUSTOM_NUGET_REPOSITORYURL }}
      - name: Push
        run:
          dotnet nuget push ./output/*.nupkg
          --source ${CUSTOM_NUGET_SOURCE}
          --api-key ${CUSTON_NUGET_APIKEY}
        env:
          CUSTON_NUGET_APIKEY: ${{ secrets.CUSTON_NUGET_APIKEY }}
          CUSTOM_NUGET_SOURCE: ${{ secrets.CUSTOM_NUGET_SOURCE }} #https://nuget.pkg.github.com/OWNER/index.json

